rpc: "https://rpc-initia-testnet.trusted-point.com:443"
api: "https://api-initia-testnet.trusted-point.com:443"
bech_32_prefix: "init"
chain_id: "initiation-1"
max_number_of_valdiators_ever_in_the_active_set: 100
batch_size: 30
start_height: 1000000
end_height: 2051430
log_lvl: "DEBUG"
metrics:
  governance_participation: True
  delegators: True
  validator_creation_block: True
  jails_info: True
