rpc: "http://127.0.0.1:21657"
api: "http://127.0.0.1:1311"
bech_32_prefix: "init"
chain_id: "initiation-1"
max_number_of_valdiators_ever_in_the_active_set: 100
batch_size: 400
multiprocessing: true
start_height: 800000
end_height: 2051430
log_lvl: "DEBUG"
metrics_file_name: "phase-1.json" # default metrics.json
metrics:
  governance_participation: True
  delegators: True
  validator_creation_block: True
  jails_info: True
